name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Repository
        uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install Quarto
        run: |
          # Download and install Quarto
          wget https://github.com/quarto-dev/quarto-cli/releases/download/v1.3.454/quarto-1.3.454-linux-amd64.deb
          sudo dpkg -i quarto-1.3.454-linux-amd64.deb

      - name: Install R Package Dependencies
        run: |
          Rscript -e 'install.packages(c("ggplot2", "dplyr"), repos="https://cloud.r-project.org")'

      - name: Render Quarto Document
        run: |
          quarto render 01_R_Basics/05_Simple_Plotting.qmd

      - name: Run Tests
        run: |
          echo "Placeholder: Add commands to run tests if applicable."
