# .github/workflows/ci.yml
name: Render Quarto Project

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: # Allows manual triggering

jobs:
  build-and-render:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }} # Recommended for package installs

    steps:
      - name: Check Out Repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/setup-quarto@main
        # with:
        #   version: 1.4.550 # Specify a version if needed

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'release' # Or specify a version like '4.3.2'

      - name: Cache R packages
        uses: actions/cache@v4
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-r-${{ runner.arch }}-${{ hashFiles('**/DESCRIPTION') }}-${{ hashFiles('**/renv.lock') }} # Adjust key as needed
          restore-keys: |
            ${{ runner.os }}-r-${{ runner.arch }}-

      - name: Install R Package Dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::ggplot2
            any::dplyr
            # Add other required packages here
          # Or use this if you have a DESCRIPTION file:
          # dependencies: |
          #   Remotes, Imports, Suggests

      # --- This step is now ACTIVE ---
      - name: Install TinyTeX (for PDF output)
        run: quarto install tool tinytex
      # --- End of activated step ---

      - name: Render Quarto Project
        run: |
          # Renders the project based on _quarto.yml
          # Ensure _quarto.yml exists and is configured correctly.
          # Output defaults to _site unless output-dir is set.
          quarto render
        shell: bash

      # Optional: Run tests if you have them
      # - name: Run Tests
      #   run: |
      #     Rscript -e 'devtools::test()' # Example

      - name: Upload Rendered Output
        uses: actions/upload-artifact@v4
        with:
          name: rendered-site # Name of the artifact zip file
          path: _site # Change to 'output' if configured in _quarto.yml
          if-no-files-found: error # Fail if the output dir is missing
